### ISSUE TITLE
Swing wallet price information not showing in Linux.

### ISSUE THREAD

**Issue by treepi3** [ZencashOfficial/zencash-swing-wallet-ui#102]
I've been having trouble getting the pricing information to work on Pop_OS 18.04 which is Ubuntu 18.04 underneath.

When running the swing node on Arch, though I was able to see this data. I tried Googling for an open issue and solution but couldnt find one.

![screenshot from 2018-05-29 09-48-32](https://user-images.githubusercontent.com/13264659/40666490-78a7325e-6325-11e8-8a98-46b2507ec701.png)

**Comment by zenportodev** [comment]
The data used to show the price/capitalization information is taken from this URL:
https://api.coinmarketcap.com/v1/ticker/zencash/
If the information is not shown, this may be due to (temporary) connectivity problems. Could you please try to open the URL on Pop_OS 18.04 with a Web browser at the same time as the GUI wallet has this problem... It would be rather strange if the price/capitalization information is not shown but the URL is accessible.

In addition the log file probably shows an error message about loading the data from:
https://api.coinmarketcap.com/v1/ticker/zencash/

The location of the wallet log files is:
```
Linux:    ~/.ZENCashSwingWalletUI/ZENCashGUIWallet_xxxx_xx_debug.log 
Windows:  %LOCALAPPDATA%/ZENCashSwingWalletUI/ZENCashGUIWallet_xxxx_xx_debug.log
Mac OS:   ~/Library/Application Support/ZENCashSwingWalletUI/ZENCashGUIWallet_xxxx_xx_debug.log
```

**Comment by Aphiso** [comment]
```
[Thread-7] [Wed May 30 23:26:42 CDT 2018] [WARNING] Could not obtain ZEN exchange information from coinmarketcap.com due to: javax.net.ssl.SSLException java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty 
[Thread-7] [Wed May 30 23:26:42 CDT 2018] [INFO] Gathering of ZEN Exchange data done in 48ms. 
```

**Comment by zenportodev** [comment]
The error indicates that the JDKs SSL trust store (containing certificates) is misisng or otherwise inaccessible/unusable. Depending on exactly which JDK is used on Pop_OS 18.04 the underlying cause may be one of several. Maybe the JDK SSL certificates are in a separate package, that is not installed or not configured etc:
https://stackoverflow.com/questions/6784463/error-trustanchors-parameter-must-be-non-empty

Do you run the wallet from the Ubuntu DEB package? What version of java is used to run the wallet?

**Comment by zenportodev** [comment]
JDK 11 is the current version being developed, so there may be problems with it. The ZENCash Desktop GUI Wallet is indeed tested mostly with JDK 8. If the problem still persists with open-jdk8, I am not sure what the reason could be. Some guesses: maybe parts of the JDK 11 remain (the SSL trust store) and maybe JDK 8 tries to use them...

**Comment by finpunk** [comment]
is this still an open issue @zennermac?

**Comment by zennermac** [comment]
@finpunk we need to check if this is still an issue, very likely not.

**Comment by cronicc** [comment]
Swing is in pure maintenance mode, no new features will be implemented anymore. Only critical bug fixes and compatibility releases for zend deprecations are being done.
