### ISSUE TITLE
Rename to `Swing`

### ISSUE THREAD

**Issue by tarrenj** [ZencashOfficial/zencash-swing-wallet-ui#114]
The wallet is referred to as `Swing` everywhere, but the wallet itself.  This adds confusion.  We should clearly indicate the name within the wallet itself.

**Comment by Spiral11** [comment]
People come on the discord confused whether they have the Swing wallet as there is no mention of the word "Swing" in the wallet itself despite this github being named zencash-swing-wallet-ui and the wallet being referred to as "Swing" pretty much everywhere.

https://github.com/ZencashOfficial/zencash-swing-wallet-ui/releases
Releases should be tagged as "ZenCash Swing Wallet" rather than "ZenCash Desktop GUI Wallet"

https://cdn.discordapp.com/attachments/334085157441110017/461612664280580096/unknown.png
Title bar should be "ZenCash Swing Wallet" instead of "ZenCash Desktop GUI Wallet"

**Comment by Jzarecta** [comment]
Usually the main wallet done by the team is referenced as 'Core' even thought technically is Qt wallet. In this case it uses Java Swing but still the core node so it should be **ZenCash Core**

**Comment by Spiral11** [comment]
@Jzarecta That may be technically correct but I don't think it would be wise to rename the wallet to something new entirely now after it has been known as Swing for so long. I believe the new flagship wallet is also full-node and has not had it's actual name announced yet so perhaps zencash core could be a name candidate for that wallet instead, especially since if it it as good as what has been hinted at it will likely make swing obsolete anyway.

**Comment by Jzarecta** [comment]
I also think Swing is a bit _odd_ name just because the toolkit that was built on was Java Swing.

**Comment by St3x** [comment]
Is this issue still relevant ?
