### ISSUE TITLE
zencash wallet error

### ISSUE THREAD

**Issue by Sodelll** [ZencashOfficial/zencash-swing-wallet-ui#119]
I reinstalled the wallet because i was getting that code 1 error but now i get another one. It is 99% synced and this appears
![qw12](https://user-images.githubusercontent.com/36326404/43021152-429f1f0e-8c6b-11e8-9ee9-8f42a741f01a.png)

**Comment by zenportodev** [comment]
This problem is unusual (never seen this particular error message before). It could indicate some sort of socket communication issue between the zend.exe and zen-cli.exe executables that the GUI runs. Before any measures are taken to investigate, it is a good idea to backup the wallet and make sure you are using the latest version: https://zencash.atlassian.net/wiki/spaces/ZEN/pages/7176693/ZENCashWallet+Swing+Wallet+-+Backup+and+Upgrade

The wallet.dat file must never be lost! It may be copied manually when the GUI wallet/zend are not running. The wallet.dat needs to be backed up regularly (not just once - say after every few outgoing transactions) and it MUST also be backed up after creating a new Z address.

So after backups are secured the problem may be investigated by examining the logs of the GUI:
Windows:  `%LOCALAPPDATA%/ZENCashSwingWalletUI/ZENCashGUIWallet_xxxx_xx_debug.log`
and of the ZEN core/node (zend.exe):
Windows:  `%APPDATA%/Zen/debug.log`

**Comment by zenportodev** [comment]
The message "[warn] ... Only one usage of each socket address (protocol/network address/port) is normally permitted" is reported by zen-cli.exe as it gets called by the GUI. However this message is unexpected and prevents the GUI from working properly. The message indicates that the system is somehow short of network resources/sockets. Is it possible that there are other applications on the system that use the network intensively (e.g. servers/torrent clients etc)? If there are other such apps it may be a good idea to try restartng the system and running the wallet only... to see if the issue will occur again.

One article that contains ideas on solving similar problems is: https://support.socketlabs.com/index.php/Knowledgebase/Article/View/61

**Comment by St3x** [comment]
This is how I recovered my wallet on Windows 10 :
- Have a backup of your private keys (Wallet -> Export private keys...) or your `%APPDATA%\zen\wallet.dat` file (if you can't open the Swing Wallet for some reason)
- Uninstall/Delete the existing Swing Wallet and the `%APPDATA%\zen` directory
- Download, extract and run the latest [release](https://github.com/ZencashOfficial/zencash-swing-wallet-ui/releases)
    - Don't replace anything, let it start the synchronization with a brand new and empty wallet
- With the private keys simply use the Wallet -> Import private keys... menu and import your private keys
- With the `%APPDATA%\zen\wallet.dat` file there can be version-related issues so you have to extract your private keys from the file :
    - Go to https://myzenwallet.io/
	- Settings (cog) -> Load wallet.dat -> Close (cross)
	- Select wallet.dat file
	- Export -> Download Private Keys
	- Now in the Swing Wallet use the Wallet -> Import private keys... menu and import your private keys
- You will see all your funds when the Swing Wallet will be fully synchronized

Can this issue be closed ?

**Comment by Sto1cNate** [comment]
@zennermac should be able to close this one.
