### ISSUE TITLE
Can't delete messaging contacts, and contact exchange only offered when contact added

### ISSUE THREAD

**Issue by ArrEssJay** [ZencashOfficial/zencash-swing-wallet-ui#13]
Contacts can only be deleted by removing the contact_XXXX folder that refers to them.

This is a problem as the offer of exchanging your identity with someone is only made when the contact is initially added.

If the offer is not taken up or there is a problem, say, lack of balance to send the message, the only way to do the contact exchange is to quit, delete the contact file and try again.

Not a showstopper but it's a bit of a messy workaround.

**Comment by vaklinov** [comment]
I am planing to add the ability to delete/ignore contacts and to make it easier to exchange identities. This issue will stay open until those features are in place (I will notify you then). If the automatic exchange of messaging identity does not work (e.g. due to missing balance) the preferred way to do it is to export your identity as a file and share this file with the remote contact. This too may be inconvenient but it is safer than manually deleting contacts.

Later when implemented, you will be able to right-click on a contact and re-send your messaging identity to him as a special message.

**Comment by vaklinov** [comment]
There is some progress on this issue: The feature of removing contacts from the messaging contact list and ignoring their messages has been completed. It is now a part of the Git master branch.

**Comment by vaklinov** [comment]
The latest version of the wallet (0.74.6 - available in the Git/master branch) has an enhancement feature: a context menu on the users in the contact list. The options include the possibility to (re)send the sender's contact details/messaging identity subset as an identity carrying message. This is handy if the user did not manage to send contact details initially due to missing ZEN balance or similar...

With this, I think the present issue is fixed.

**Comment by Sto1cNate** [comment]
@zennermac should be able to close this one.
