### ISSUE TITLE
Poll for some fiat values

### ISSUE THREAD

**Issue by ebadiere** [ZencashOfficial/zencash-swing-wallet-ui#19]
As a miner I would like to be able to see my ZenCash balance in a common fiat currency. Code is worth a thousand words, so I got something working but I can't push it up :) 

It simply polls the coincap REST API for the USD and EUR values of the ZenCash balance.
 
Let me know what you think.

**Comment by vaklinov** [comment]
Accepted as an enhancement to be implemented.

**Comment by CoinKraken** [comment]
This is a must have. There can't be a worst thing to have to deal with than having to go back and forth between my iPhones crypto wallet and a website that doesn't offer the option of viewing your coins value in US dollars, and I have to keep checking the price in my wallet vs the price in the decimal point set up. There can't be a more of a nuisance.
More importantly, if I as a veteran of crypto can't convert the 0.009758000 over to US dollars, ho  does it impact people waiting to get into the game? if it leaves new users with a unsure, mostly negative feeling & if their first experience ends because they can't fully understand this new thing, their bodys natural defense is going to be peaking. Saying somethings wrong, step away.

**Comment by ebadiere** [comment]
I agree with the "first experience" argument, however I don't think the swing wallet runs on mobile phones.  Correct me if I am wrong.  The wallet is however used by miners and secure node operators and is a production system.  So I really want this feature, but I want it implemented with a certain level of quality.  USD's and EURs can be a start, but Asian and South American currencies should also be supported in the future.

**Comment by St3x** [comment]
The latest [release](https://github.com/ZencashOfficial/zencash-swing-wallet-ui/releases) shows the balance in ZEN and USD.
Is this issue still relevant or can it be closed ?

**Comment by Sto1cNate** [comment]
@zennermac should be able to close this one.
