### ISSUE TITLE
"Send cash" sent to wrong address

### ISSUE THREAD

**Issue by scfredricks** [ZencashOfficial/zencash-swing-wallet-ui#21]
ZENCash Desktop Wallet UI 0.74.2

I used "Send cash" to send to a "t" address, but the transaction log on the Overview screen is showing that the transaction went to a different "zn" address.

![image](https://user-images.githubusercontent.com/33385187/32411510-a583e090-c1a1-11e7-80ba-216b798a0117.png)

![image](https://user-images.githubusercontent.com/33385187/32411512-cdc4b228-c1a1-11e7-9ebd-41ec8f8e83d4.png)

**Comment by vaklinov** [comment]
The address starting with t1 is not a ZEN T address (not created by a ZEN wallet). It probably comes from ZClassic. ZENCash can send money to such an address since it is compatible with the (old) ZClassic address format. However the address is re-encoded in ZEN format starting with zn. This is a feature of the ZEN core software.

@scfredricks Where does this t1... address come from?

**Comment by scfredricks** [comment]
Thank you for the update.  I am new to ZEN/ZEC mining and got the two of them confused.  The address came from Kraken where I was trying to deposit my mined ZEN (which is not supported by them).
