### ISSUE TITLE
linux wallet download err  quick,quick

### ISSUE THREAD

**Issue by guodong1010** [ZencashOfficial/zencash-swing-wallet-ui#70]
run: sudo apt-get update
W: Failed to fetch https://zencashofficial.github.io/repo/dists/trusty/main/binary-amd64/Packages  HttpError404
W: Failed to fetch https://zencashofficial.github.io/repo/dists/trusty/main/binary-i386/Packages  HttpError404

https://zencashofficial.github.io/repo/

**Comment by cronicc** [comment]
We do not have a package for Ubuntu trusty, AFAICR there are dependency issues when trying to install the xenial package on trusty. But you can try to replace all occurrences of `trusty` with `xenial` in `/etc/apt/sources.list.d/zen.list`  and then try again.

**Comment by MHTheCount** [comment]
Am having a similar problem with Linux Mint 17
W: Failed to fetch https://zencashofficial.github.io/repo/dists/rafaela/main/binary-amd64/Packages  HttpError404

W: Failed to fetch https://zencashofficial.github.io/repo/dists/rafaela/main/binary-i386/Packages  HttpError404

E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by vaklinov** [comment]
@MHTheCount Your problem is strictly speaking not an issue in the GUI wallet but in the ZEN apt repository. The current Linux distributions supported are:
https://github.com/ZencashOfficial/repo/tree/master/dists
and Linux Mint 17 (rafaela) is clearly not among them. You may open an enhancement request in the ZEN apt repository project to have this added:
https://github.com/ZencashOfficial/repo/issues

**Comment by cronicc** [comment]
Trusty and Linux Mint added to aot repo, see https://github.com/ZencashOfficial/zencash-swing-wallet-ui/issues/73#issuecomment-368325988
