### ISSUE TITLE
Overview pane Exchange information table overlaps with System information in not maximised state

### ISSUE THREAD

**Issue by aballaci** [ZencashOfficial/zencash-swing-wallet-ui#71]
Windows 10
![zencash-wallet-0 80 2](https://user-images.githubusercontent.com/4948629/36346198-35147ef0-143a-11e8-801f-a5c741b1e5b9.png)

**Comment by vaklinov** [comment]
The latest Git master branch contains the new look of the wallet. It has not been fully tested on all OSes yet. It appears in this case the default Windows 10 fonts are enlarged by 20% or so and this causes the problem. It needs to be fixed in a way that makes it flexible/not dependent on font scaling.
