### ISSUE TITLE
ZenCash Swing wallet installation problem in Linux Mint 17

### ISSUE THREAD

**Issue by MHTheCount** [ZencashOfficial/zencash-swing-wallet-ui#73]
Greetings,
I have tried to install the ZenCash Swing wallet in Linux Mint 17 using the commands in Terminal as follow:**

sudo apt-get update
sudo apt-get install apt-transport-https lsb-release

echo 'deb https://zencashofficial.github.io/repo/ '$(lsb_release -cs)' main' | sudo tee --append /etc/apt/sources.list.d/zen.list
gpg --keyserver ha.pool.sks-keyservers.net --recv 219F55740BBF7A1CE368BA45FB7053CE4991B669
gpg --export 219F55740BBF7A1CE368BA45FB7053CE4991B669 | sudo apt-key add -

sudo apt-get update
sudo apt-get install zen zencash-desktop-gui-wallet

I get back 
W: Failed to fetch https://zencashofficial.github.io/repo/dists/rafaela/main/binary-amd64/Packages  HttpError404

W: Failed to fetch https://zencashofficial.github.io/repo/dists/rafaela/main/binary-i386/Packages  HttpError404

E: Some index files failed to download. They have been ignored, or old ones used instead.

Any ideas out there to fix this, please? Thanks

**Comment by vaklinov** [comment]
@MHTheCount The problem is strictly speaking not an issue in the GUI wallet but in the ZEN apt repository. The current Linux distributions supported are:
https://github.com/ZencashOfficial/repo/tree/master/dists
and Linux Mint 17 (rafaela) is clearly not among them. You may open an enhancement request in the ZEN apt repository project to have this added:
https://github.com/ZencashOfficial/repo/issues

As a workaround you may take the binary packages and install them manaully:
https://github.com/ZencashOfficial/repo/raw/master/pool/main/z/zcash/zen_2.0.11_amd64.deb
https://github.com/ZencashOfficial/repo/raw/master/pool/main/z/zencash-desktop-gui-wallet/zencash-desktop-gui-wallet_0.73.6_all.deb

BTW: The GUI wallet version in the apt repository is a bit old. I expect to make a new release soon (next week).

**Comment by cronicc** [comment]
I've added all Linux Mint Releases that are currently supported to the apt repo, but haven't tested if the packages install there. As the packages are built and packaged on Ubuntu Xenial you might run into dependency issues.  @MHTheCount please report back here and feel free to reopen the issue if the packages don't work for you.
