### ISSUE TITLE
wallet error message -1

### ISSUE THREAD

**Issue by burciuleasca** [ZencashOfficial/zencash-swing-wallet-ui#90]
Hello

When I try to open my wallet I get this strange message saying it cannot connect to server error code -1

Please help me solve this problem

Thanks

**Comment by zenportodev** [comment]
The problem may be due to a wallet being too old (older releases had the problem of more frequent block index database corruption). If the wallet is too old, you need to update to the newest version. If the problem continues, you need to re-index the blockhain.

The ZEN private keys are located in the wallet.dat file in directory:
Windows: %APPDATA%/Zen/
Mac OS: ~/Library/Application Support/Zen/

To make sure your ZEN is not lost, the most important thing is to keep a backup copy of your wallet.dat file - it must never be lost! It may be copied manually when the GUI wallet/zend are not running. The wallet.dat needs to be backed up regularly (not just once - say after every few outgoing transactions) and it MUST also be backed up after creating a new Z address.

This document explains how to update the wallet and reindex:
https://documentation.zencash.com/pages/viewpage.action?pageId=1148493
The following guide for Windows is also handy:
https://miningwithnvidia.com/2018/02/09/zencash-wallet-eof-reached-code-1/

**Comment by St3x** [comment]
This is how I recovered my wallet on Windows 10 :
- Have a backup of your private keys (Wallet -> Export private keys...) or your `%APPDATA%\zen\wallet.dat` file (if you can't open the Swing Wallet for some reason)
- Uninstall/Delete the existing Swing Wallet and the `%APPDATA%\zen` directory
- Download, extract and run the latest [release](https://github.com/ZencashOfficial/zencash-swing-wallet-ui/releases)
    - Don't replace anything, let it start the synchronization with a brand new and empty wallet
- With the private keys simply use the Wallet -> Import private keys... menu and import your private keys
- With the `%APPDATA%\zen\wallet.dat` file there can be version-related issues so you have to extract your private keys from the file :
    - Go to https://myzenwallet.io/
	- Settings (cog) -> Load wallet.dat -> Close (cross)
	- Select wallet.dat file
	- Export -> Download Private Keys
	- Now in the Swing Wallet use the Wallet -> Import private keys... menu and import your private keys
- You will see all your funds when the Swing Wallet will be fully synchronized

Can this issue be closed ?

**Comment by Sto1cNate** [comment]
@zennermac should be able to close this one.
